[package]
name = "pachadb-backend-cloudflare"
version = "0.1.0"
edition = "2021"

[dependencies]
pachadb-core = { path = "../core", version = "*" }

worker.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_derive.workspace = true
