name = "pachadb-examples-cloudflare-simple"
main = "build/worker/shim.mjs"
compatibility_date = "2023-07-24"

usage_model = "bundled"

[build]
command = "cargo install worker-build && worker-build --release"

# kv_namespaces = [
#   { binding = "playground-pachadb-entities-store", id = "f65a15f705814e5eb00202ef19ed27ca" },
#   { binding = "playground-pachadb-facts-index-by-entity", id = "f2780bd63f1a4c81be67a8f75fe52d22" },
#   { binding = "playground-pachadb-facts-index-by-entity-field", id = "df3df3088fe64c9b8f2c616f312dbd09" },
#   { binding = "playground-pachadb-facts-index-by-field", id = "5780f94195774bdfa5519f76c951999d" },
#   { binding = "playground-pachadb-facts-index-by-field-value", id = "be25916199f54ca698d26fcc1e543306" },
#   { binding = "playground-pachadb-facts-index-by-value", id = "5f2051b170984d979a7da8580d9cd83f" },
#   { binding = "playground-pachadb-facts-store", id = "88c04e76bdb04ff78783cc5d850c86ac" },
#   { binding = "playground-pachadb-tx-store", id = "4efeddcbd90b4d3aa9e76b9efb01867c" },
# ]
#
# [durable_objects]
# bindings = [{ name = "PLAYGROUND_PACHADB_TX_MANAGER", class_name = "DurObjTxManager" }]
#
# [[queues.producers]]
# queue = "playground-pachadb-facts-indexing"
# binding = "playground-pachadb-facts-indexing-queue"
#
# [[queues.producers]]
# queue = "playground-pachadb-facts-consolidation"
# binding = "playground-pachadb-facts-consolidation-queue"
#
# [[migrations]]
# tag = "v1"
# new_classes = ["DurObjTxManager"]
